contributors.html, script.js, styles.css
=> add Display contributors dynamically

script.js, styles.css, templates.html, templates/timer.html
Added a new Countdown Timer Template to the Templates Gallery.
Created a visually appealing timer component
Integrated animation and responsive design
Linked the template through templates/timer.html
Ensured consistency with existing template structure and styling
Fixes #{19}
- [✅ ] New feature ✨
- [✅ ] My code follows the style guidelines of this project
- [✅ ] I have performed a self-review of my code
- [✅ ] I have added tests that prove my fix is effective or that my feature works
- [✅ ] I have linked the issue using `Fixes #issue_number`
=> Added Countdown timer template

contact.html, contributors.html, index.html, script.js, styles.css, templates.html
**Fixes #2** 
This PR adds a modern animated cursor effect across all pages using a smooth, snake-style trailing animation with a blue gradient theme.
**What’s Implemented:**
Introduced a JavaScript-based cursor trail animation.
Dots follow the mouse pointer with a smooth easing effect.
Applied a blue gradient with blur and scale transitions for a modern look.
Reusable logic placed in script.js and included across all HTML pages.
Styled via centralized rules in style.css.
**🎨 Visual Improvements:**
Adds a dynamic, interactive layer to the UI.
Enhances overall user experience and engagement.
Fully responsive and lightweight – no external libraries used.
**Tested On:**
index.html
contributors.html
templates.html
contact.html
https://github.com/user-attachments/assets/30c18957-247b-44fc-b0d7- …
=> ✨ Enhance Cursor with Blue Gradient Snake Trail Animation

contact.html, contributors.html, index.html, styles.css, templates.html
This PR enhances the UI/UX of the Navbar and Footer across the website for a cleaner, more modern, and responsive experience. The improvements include design consistency, better accessibility, and improved structure.
Fixes #1 
Navbar:
Added solid background color for better visibility
Improved logo styling (padding, size, font-weight)
Enhanced active link indicator with smooth transition
Applied hover effects and cleaner spacing
Integrated responsive design for better mobile support
Footer:
Added new footer section with better layout
Included social links (GitHub, LinkedIn, Email)
Improved typography and spacing
Made the footer mobile responsive and aligned with overall theme
https://github.com/user-attachments/assets/48f3f69d-99b4-4545-8ac3-5ba368d12f49
kindly merge it @AnujShrivastava01
=> Navbar and Footer Enhancement

templates/button.html
Hover Button UI with Gradient and Glowing Effect
Fixes #55
This pull request improves the styling of the hover button to make it more visually appealing and user-friendly. The changes include:
1. Addition of 3 more buttons in alignment to other buttons.
2. On hovering the buttons we can see the glowing effect on the buttons .
3. On clicking the button the background color(black)become transparent and we can see the gradient.
These changes are purely visual and do not affect any functionality. The goal is to enhance the user interface and user experience (UI/UX).
=> Added  Glowing hover button on Hover page

index.html, styles.css
Fixes #13
Further modernized the footer icons and added animations. Changed the color coding for QOL UI.
Fixes Issue #13
- [✔ ] New feature ✨
- [ ✔] Code refactor 🔨
- [✔ ] My code follows the style guidelines of this project
- [ ✔] I have performed a self-review of my code
- [ ✔] I have linked the issue using `Fixes #issue_number`
Before
After
(Beat Animated icons)
Requesting font change task assignment.
=> Add footer animations and icons

templates.html, templates/neumorphic.html, templates/social-share-buttons.html
Fixes #214 
------------------------
-------------------------
=> ✨ Added feature: Neuromorphic-button effects

templates.html, templates/navbar.html
I've added the navbar variants template. 
- Sticky Header
- Hamburger Menu.
I've included the visual demo of each variant so that the user can easily understand each feature & the "show code" property to see & use each feature's code in their own projects.
please review it & let me know if any changes required ,I'm down for any improvements.
Fixes : #201 (assigned work)
Little Bug fixed -
While adding my template I came across a small bug in previously merged work of another contributor (no closing tag "article" in Neumorphic Button Effects) so I have also fixed it.
Thank You!
=> Add navbar variants template

styles.css
Fixes #131
Related to responsiveness
=> fixed the issue

templates/login.html
✨ Added 5 templates the login page ui templates with updated templates
🔧 Replaced old forms with responsive versions using TailwindCSS
✅ Tested on multiple screen sizes
---
=> Added updated login UI templates with animations

contact.html, styles.css
Improve Contact Page Layout with Margin and Padding Adjustments
Please check
=> Add improve contact page 

CONTRIBUTING.md
Added a clear and beginner-friendly CONTRIBUTING.md file to help new contributors understand the process of contributing to the project.
Fixes #124 
- [x ] Documentation update 📚
- [x ] My code follows the style guidelines of this project
=> Added CONTRIBUTING.md with detailed guide

index.html
This PR updates the homepage content of AnimateItNow to improve clarity, consistency, and engagement. The goal is to better communicate the project’s mission, simplify contribution steps, and highlight the importance of open source.
Fixes #253
=> Update Request for AnimateItNow

templates.html
issue #376
This update adds a fully functional and responsive **search bar** to the **Template Gallery**, allowing users to filter templates in real-time based on their name (and optionally tags in the future).
---
Previously, users had to scroll through the entire Template Gallery to find a desired template. With this enhancement, users can now **instantly filter** templates using a search input, making navigation faster and smoother.
---
- 🔎 **Search Input** added at the top of the Template Gallery
- ⚡ **Real-time Filtering** of templates based on:
- Template title/name
- (Structure supports future filtering by tags/categories)
- 📭 **No Results Found** message when query doesn't match any template
- 📱 **Fully Responsive** and integrated cleanly with existing layout
- 💨 **No Page …
=> added Search Functionality in Template Gallery

styles.css
<!-Changed the alignment of footer left and footer right to center when that app will be running on mobile 
-Bug fixed 
-Aligned the footer items to center.
=> fixed footer alignment

.github/workflows/greet.yml, glassmorphismstyle.css, templates/glassmorphism.html
Added more designs and show code button for each design in the glassmorphism profile card section from the template gallery
Fixes #335
=> Added more designs and show code button in glassmorphism profile card

templates.html, templates/display.html
I've added a template for Display properties , visually demonstrating difference between inline , block with its code snippets
Fix : #272
Its preview 
The template 
Please review it & let me know for any further changes. Thank you!
=> Added display properties card

index.html
Added a new Leaderboard button to the navbar in index.html, which links to the newly added leaderboard.html page.
The button is fully responsive and consistent with the existing navbar styling and layout.
Fixes #460
=> Add Leaderboard button to navbar

templates/loader.html
Wrapped all loaders inside a blurred and styled container using CSS. 
This improves the UI by grouping loaders in a visually appealing section with better separation from the background.
Fixes #403
##✅ Checklist
This PR focuses purely on visual improvement of the loader section by adding a container with a blur effect and styling. No individual loader animation styles were changed.
=> Improved loader visibility by  adding a  container with blur effect

about.html, contact.html, contributors.html, script.js, templates.html
This PR fixes the snake cursor bug that was previously not functioning as expected. The cursor animation is now working consistently across all relevant pages. Unnecessary or broken code was cleaned up, and styling conflicts have been resolved.
Fixes #437 
https://github.com/user-attachments/assets/d078a4cc-31a9-4294-9a43-8fa01642c118
=> Snake curl  

index.html, styles.css
I have added label to snake toggle button, now it clearly shows what that toggle button do.
Fixes #504
=> Added label to snake-cursor toggle

index.html
Fixes #497 
- [ ✅] Bug fix 🐛
- [ ✅] My code follows the style guidelines of this project
- [ ✅] I have performed a self-review of my code
- [✅ ] I have linked the issue using `Fixes #issue_number`
=> Fixed FAQ bug . 

templates/toggles-and-checkboxes.html
Added a new feature **Orbit Flip Toggle** with a copy code option.
N/A
This PR introduces a new circular toggle where the handle orbits halfway around like a Newton's Cradle motion, along with a copy-code button for easy integration.
=> Added A New Toggle Name Orbit Flip

index.html, sandbox.html, script.js, templates.html, templates/display.html
This pull request introduces a lightweight **sandbox feature** that allows users to dynamically preview HTML, CSS, and JavaScript code. The feature uses an `iframe` and `Blob` to securely execute user-provided code in real time.
---
-  Added sandbox rendering logic using `iframe` and `Blob`
-  Ensured safe execution and reloading of previews
-  Basic UI support for live preview window
---
---
N/A (First implementation)
---
This sets the groundwork for future features like saving code, sharing previews, or adding console output.
finishes #400
=> Adding a SANDBOX feature

templates/neuromorphic-gallery.html
📌 Description  
This enhancement improves the UI experience by introducing **neuromorphic-style Level Cards** for Level 1, 2, and 3. The main goal was to elevate the visual aesthetics of the card section while ensuring responsiveness and interactivity.
- ✅ Soft **neuromorphic card design** using layered shadows and light gradients for a modern, smooth appearance  
- ✅ Beautiful **Level buttons** in distinct colors (L1 - Sky Blue, L2 - Lime Green, L3 - Coral Red) to make navigation intuitive and visually appealing  
- ✅ **Dark/Light mode toggle** with seamless background color transitions to reduce eye strain and suit user preferences  
- ✅ **Hover animations** on cards that gently scale and glow to provide interactive feedback  
- ✅ **Responsive layout** built using Flexbox to ensure …
=> Added Neuromorphic Level Cards with Dark/Light toggle (GSSoC25)

templates/tooltip.html
i have added fade animation tooltip feature and add conclusion i have fix side bar issue 
Fixes #{493}
add 2 new feature 
fix side bar
=> Enhance tooltip feature

templates/glassmorphism.html
Feature implemented :
- Interactive flip animation on tap (front -> back and back -> front)
- Clean glassmorphism UI with blur & transparency effects
- Profile image and personal details on the front
- Contact / social information on the back
- Fully responsive and centered layout using Flexbox
File Updated:
- Template/glassmorphism.html
- CSS in style tag 
screenshot :-
=> Added a new template in glassmorphism profile card

about.html
Enhances the About Page by adding a new section titled **"Why Choose AnimateItNow?"** that highlights the platform’s core benefits.  
This section includes 3 visually styled cards (Super Fast Templates, Beginner Friendly, Modern UI Components) — built using **pure HTML & CSS** — to help users quickly grasp the strengths of AnimateItNow.
Fixes #561 
None
No JavaScript was used. This feature was implemented using **only HTML & CSS** to keep it lightweight, accessible, and beginner-friendly.
=> ✨ Add 'Why Choose AnimateItNow?' section with benefit cards to About Page

contributors.html, styles.css, templates.html
There were several glitches like unwanted bands on these pages. Now they are working in both Dark mode and Light mode
Fixes #626
=> Fixed the glitches from contact,templates & contributors page

templates.html
The responsiveness of page "Templates.html" was not working. 
Fixes #655
=> Fixed the navbar issue on templates page

contributors.html, styles.css, templates.html
Fixes #636
This PR enhances the UI of the Contributors Page by:
- Adding transparent glassmorphism effect with backdrop blur to contributor cards
- Improving the heading with a smooth gradient for better visual depth
- Ensuring full support for dark theme compatibility
These changes aim to create a more engaging, modern, and visually appealing user experience.
#screenshort-
https://github.com/user-attachments/assets/c7acd3b3-9405-4d87-a996-29c506bfbdbb
=> 🚀Enhance Contributors Page UI with Glassmorphism and Dark Mode Support

templates/loader.html
This PR fixes the issue of distortion of spinner loader when size is increased.
Fixes #565 
https://github.com/user-attachments/assets/e5bd10c1-645a-497b-9963-78b8d148b0a2
=> Fixed spinner loader size issue

styles.css, templates.html, templates/accordian.html
Fixes #{572}
- [] New feature ✨
- [] My code follows the style guidelines of this project
- [] I have performed a self-review of my code
- [] I have commented my code, particularly in hard-to-understand areas
- [] I have added tests that prove my fix is effective or that my feature works
- [] I have linked the issue using `Fixes #issue_number`
=> added accordian template

leaderboard.html
Added the loading effect inplace of plain text
Added point indication infront of levels
Minor fixes in code
Fixes #714
=>  Enhaced the loading effect, added point indication & minor fixes

styles.css, templates/CardHoverEffects.html, templates/LoginFormGlassMorphism.html, templates/accordian.html, templates/animated-btn.html, templates/button.html, templates/carousel.html, templates/code_playground.html, templates/display.html, templates/feature.html, templates/glassmorphism.html, templates/hero.html, templates/loader.html, templates/login.html, templates/modal.html, templates/navbar.html, templates/neumorphic.html, templates/page_not_found_template.html, templates/social-share-buttons.html, templates/text_effects_anim.html, templates/toggles-and-checkboxes.html, templates/tooltip.html
Attached same navbar in all the template designs 
Fixes #731 
For reference:
=> Added the same navbar all over the templates

templates/login-form-ui.html
Added a new login form UI using HTML and CSS. The form is clean, responsive, and ready to be integrated into the templates section. No images or external assets used.
Fixes #N/A
None
=> Added login form UI component

index.html
-  Added multiple CSS animations (rotate, bounce, zoom)
- Styled placeholders and improved visual design
- Cleaned up code and final version for review
=> Added animations and enhanced input styling

templates/2d_transform.html
=> Add template for 2D CSS transforms

privacy.html
solved issue #680  -added privacy policy page:
=> solved issue #680 -added privacy policy page

styles.css, templates.html, templates/CardHoverEffects.html, templates/LoginFormGlassMorphism.html, templates/animated-btn.html, templates/carousel.html, templates/display.html, templates/feature.html, templates/glassmorphism.html, templates/hero.html, templates/loader.html, templates/login.html, templates/navbar.html, templates/neumorphic.html, templates/social-share-buttons.html, templates/tooltip.html
Added syntax highlighting support to the project by integrating a highlighting library and updating the structure of the code blocks with appropriate language classes.
Fixes #674 
(this is just example i have changed in every templates)
This pull request is linked to a Level 2 issue assigned under GSSoC.
This feature involved significant effort, including restructuring HTML, applying semantic tags, and integrating a syntax highlighting library. I’ve ensured it works across all variants and does not break existing UI/UX.  
Since this is marked as a **Level 2 issue**, and required substantial code updates and testing, I kindly request the maintainers to review and marked as a **Level 3 issue** and merge it carefully.  
I’m excited to contribute further and hope this helps me gain more …
=> Syntax highlighting

styles.css, templates.html
Refined Template Page UI:
- Updated the Search Bar styling and behavior
- Added consistent spacing between major elements
- Improved grammar for a more professional appearance
Fixes #663
https://github.com/user-attachments/assets/74130e07-0fea-4f33-9389-03239f023f19
=> Enhanced template page UI with spacing and search bar animation

leaderboard.html
#814   Fixed footer of leaderboard page.
**Earlier:-**
**After my fix:-**
@AnujShrivastava01 Please review and accept this PR if everything is fine.
Thanks
=> fixed footer of leaderboard.html

leaderboard.html
The Horizontal scroll was appearing on small screen on leaderboard page
Fixes #748
=> Fixed the horizontal scroll

templates/contact.html
fixes #881 
Updated Contact Us page with a cleaner, responsive design.
Enhanced form styling for better usability.
Added contact info section with icons.
Integrated interactive code preview with copy-to-clipboard functionality.
=> Revamp Contact Us page with modern template

about.html, contact.html, contributors.html, index.html, leaderboard.html, playground.html, templates.html
This PR introduces two key navigation enhancements to improve user experience across the site, addressing two separate issues.
1.  **Navbar Consistency:** It fixes inconsistencies in the main navigation bar on the **Leaderboard** and **Hover-Effects** pages by adding missing links and making the header logo a clickable link to the homepage.
2.  **Clickable Footer:** It enhances the site-wide footer by making the **"AnimateItNow"** text a clickable link that also redirects the user to the homepage.
Fixes #843 
Fixes #813 
-----
-----
-----
**Before:**
**After:**
**Before:**
https://github.com/user-attachments/assets/d0f08d28-127a-4d1e-89ab-707b60ecc93c
**After:**
https://github.com/user-attachments/assets/43c199ee-5d82-44b8-88f5-2678a4f40979
-----
None beyond the two primary issues linked …
=> Feat: Enhance Header and Footer Navigation

contact.html, contributors.html, index.html, leaderboard.html, styles.css, templates.html
I have completed #73 .
What I have done is I added bouncy animation to the navbar title "Animate It Now" and changed the width of the logo. To reduce the conflicts in styles.css file, I copied from the main branch to develop my part. "Home" button and other buttons were already done by someone with a nice UI. Therefore, I skipped it.
Fixes #{ISSUE_NUMBER}
=> Fully finished navbar title(Animate It Now) animation (#73)

about.html, contact.html, contributors.html, editor.css, editor.html, editor.js, index.html, leaderboard.html
Added Dark Mode Support to Editor
Fixes #914
Light mode
Dark mode
I have made the required changes in editor.html, editor.css, editor.js to add the dark mode feature.
Hope you like the work I have done and review the changes.
Thanks for the opportunity!
=> Added Dark Mode Support

about.html, contact.html, contributors.html, editor.css, editor.html, editor.js, index.html, leaderboard.html
Fixes #916
Before
After
I have made the required changes in the footer of all html files.
Hope you like the modifications and review the changes.
Thanks for the opportunity!
=> Enhanced the Footer Form

contributors.html, contributors.js, package-lock.json, script.js
Added a new `contributors.js` file and linked it to display project contributors dynamically using GitHub API.
Fixes #962 
This feature dynamically fetches and displays contributors on the website without requiring manual updates.
=> Added contributors.js to display GitHub contributors dynamically

index.html, styles.css
🚀 Pull Request
📄 Description
- Updated hero section to enhance visual engagement and alignment.
- Replaced simple fade-in animation on heading/content with a more dynamic animation.
- Aligned the “Get Started” and side button for consistent positioning.
- Added a smooth, continuous up-down floating effect to both buttons.
Fixes #953 
🛠️ Type of Change
UI/UX enhancement 🎨
✅ Checklist
- My code follows the style guidelines of this project
- I have performed a self-review of my code
- I have commented my code, particularly in hard-to-understand areas
- I have linked the issue using Fixes #953 
📸 Screenshots 
Before:
https://github.com/user-attachments/assets/46217e88-764e-48ba-ab09-2ce7fed55043
After:
https://github.com/user-attachments/assets/842a16b7-aa41-4322-bb48-e4d36e07a724
=> Enhance Hero Section: Replace Fade-In Animation, Align Buttons, and Add Smooth Floating Effect

templates.html, templates/Like_Buttons.html
Added Animated Like/Heart Button template Fixes #888 
- [✅] I have linked the issue using `Fixes #888 `
Animated Like/Heart Buttons
[#888](https://github.com/itsAnimation/AnimateItNow/issues/888)
This PR is raised under GSSoC'25. It is a Level 2 issue raised by @DhanashriPetkar
=> ❤️Added Animated Like/Heart Button template

templates/modal.html
Added 10 designs and "Show Code" button in popup template page. It's also dark mode/light mode responsive.
Fixes #803
=> Added 10 designs and show code button in popup template

styles.css
this PR solve the alignment issue in the heading of about and home page by providing proper margin
Fixes #818 
- [/ ] enhance
- [/ ] My code follows the style guidelines of this project
- [ /] I have performed a self-review of my code
- [ /] I have commented my code, particularly in hard-to-understand areas
- [ /] I have added tests that prove my fix is effective or that my feature works
- [ /] I have linked the issue using `Fixes #issue_number`
=> ENHANCE : the alignment issue  in bte heading of about page and home page 

generator.css, generator.html, generator.js, templates.html
Fixes #817
This PR implements a **CSS Snippet Generator** feature that allows users to generate and copy custom CSS code for:  
-  **Box shadows**  
-  **Gradients**  
-  **Border-radius**  
The generator provides a lightweight, interactive tool for both **quick prototyping** and **learning CSS**.  
---
---
---
- The feature is built with **native HTML inputs** and **pure JavaScript** for a lightweight, dependency-free solution.  
- Files added/updated:  
- `generator.html`  
- `generator.css`  
- `generator.js`  
- Navigation updated to link to the generator page.  
- ✅ Code written  
- 🔄 Integration and testing thoroughly conducted
=> Feat: CSS Snippet Generator

leaderboard.html
=> Fix: search-icon was misplaced, fixed now

signup.html
Fixes #1220
-The Signup dialog box now redirectly to Login page.
=> Fix: Login here(in signup dialog box) redirects to Login page now.

script.js, styles.css
Close : #1218 
The FAQ section on the homepage had a toggle functionality issue. Clicking on FAQ items did not properly expand or collapse the answers.  
The `toggleFAQ()` JavaScript function existed but was not working as expected due to event handling issues.
---
- Simplified the `toggleFAQ()` function in `script.js` to directly toggle the `active` class on the FAQ item.  
- Removed unnecessary complexity in the FAQ toggle logic.  
- Ensured proper CSS transitions for smooth expand/collapse animations.  
- Made the `toggleFAQ()` function globally accessible.
---
The previous implementation had overly complex logic that prevented proper toggling.  
The new implementation directly toggles the `active` class on the clicked FAQ item, triggering the CSS transitions and making the FAQ section …
=> 🛠️ Fix: FAQ Toggle Functionality Issue

index.html
Close : #1223 
FAQ Toggle Functionality and Accessibility Improvements
---
The FAQ section on the homepage had several issues:
- Invalid HTML structure with `<li>` elements inside `<p>` tags.
- Lack of keyboard accessibility for FAQ items.
- Missing visual feedback for user interactions.
- No focus states for accessibility compliance.
---
- Fixed HTML structure by replacing invalid list elements inside paragraphs.
- Enhanced the `toggleFAQ()` function for better reliability.
- Added keyboard event listeners for accessibility (Enter/Space keys).
- Improved CSS transitions for smoother expand/collapse animations.
- Added visual feedback for hover and focus states.
- Enhanced overall user experience with better interactive cues.
---
**HTML Structure Fix:** Corrected invalid HTML structure in …
=> 🛠️ Pull Request: Enhanced FAQ Functionality and Accessibility

templates.css, templates.js
close: #1173
**Fix: Templates Page Alignment Issue ready to merge**  
I have resolved the **Templates page alignment issue**. Here’s a summary of the changes:
---
- Single HTML file containing **multiple `<head>` tags** and **inline styles**.  
- **Navbar** and **Templates Gallery** were misaligned due to conflicting CSS.
- Split the code into separate files:  
- `templates.html`  
- `templates.css`  
- `templates.js`  
- Removed duplicate `<head>` tags and **merged all meta, title, and stylesheet links properly**.  
- Adjusted CSS to ensure the **Templates Gallery section is centered horizontally** and has **proper spacing below the navbar**.  
<table>
<tr>
<td align="center">
<b>Before</b><br/>
</td>
<td align="center">
<b>After</b><br/>
</td>
</tr>
</table>
@SurajSG23, …
=> Update on Issue #1173 – Templates Page Alignment

index.html, styles.css
This PR fixes the layout and alignment issues in the footer section of the website.
Fixes #1228
- Bug fix 🐛
-Footer boxes (Connect With Us and Quick Links) now sit side by side on larger screens.
-On smaller screens, boxes stack vertically for a responsive layout.
-Content inside each box is properly aligned with consistent spacing.
-Adjusted .footer-right and .footer-box CSS to display the two footer boxes side by side.
-Removed conflicting width and flex properties that caused misalignment.
-Ensured proper spacing and padding between the two columns.
-Added flex-wrap: wrap to maintain responsiveness on smaller screens.
-Cleaned up list spacing for a neat appearance.
=> Fix footer alignment and layout

templates/accordian.html, templates/button.html, templates/card_hover.html, templates/modal.html, templates/tooltip.html
Inconsistent Navbar Structure Across Templates
close : #1231 
---
The project had **inconsistent navbar implementations** across different template files:
- Some templates used a simplified navbar structure with minimal navigation options.  
- Others included the full navigation with all links.  
- Users may find different navigation options depending on which template page they’re viewing.  
- Some templates had **hardcoded links** instead of relative paths, which could cause issues in different deployment scenarios.
---
Standardized the navbar structure across all template files:
- Added missing navigation links (**Editor, Playground, Login, Sign Up**) to ensure consistency.  
- Updated all navbar links to **use relative paths**.  
- Ensured the **"Templates" link** has the **active …
=> 🛠️ Pull Request: Standardize Navbar Across Templates

contact.html, styles.css, templates.css, templates.html, templates/animated-btn.html, templates/button.html, templates/hamburger-menu.html
**Issue Title:** Inconsistent Button Implementations Across Templates   #1237 
---
The project previously had multiple button implementations across templates, with each template defining its own custom CSS (e.g., `template-btn`). This led to:  
- Code duplication across files  
- Inconsistent button styling and behavior  
- Increased difficulty in maintaining a cohesive design system  
---
I standardized the button component system across the entire project by:  
✅ **Removing redundant styles**  
- Deleted all `template-btn` rules from `styles.css`, `templates.css`, and inline HTML styles  
- Cleaned up leftover commented-out button code  
✅ **Updating all HTML files to use standardized classes**  
- `templates.html` → Updated to use `btn btn-primary`  
- `templates/button.html` → …
=> Standardize Button Component System Across Project  

templates/LoginFormGlassMorphism.html, templates/forgot-password.html, templates/register.html
🚀 Pull Request
📄 Description
This PR fixes the issue where the "Forgot Password" and "Register" links in the login template were not working.  
Now both links redirect the user to their respective pages:
'forgot-password.html' for resetting password
'register.html' for new user registration
Fixes #1161 
🛠️ Type of Change
Bug fix 🐛
My code follows the style guidelines of this project
I have performed a self-review of my code
I have commented my code, particularly in hard-to-understand areas
I have linked the issue using `Fixes #1161 `
📸 Screenshots
=> Fix: Added functionality for Forgot Password and Register links in login template

leaderboard.html
Fixes: #1252  (Improve and Fix Leaderboard Page Layout & Functionality)  
- Refactored **leaderboard.html** for cleaner structure and better responsiveness.  
- Fixed broken/misaligned elements in leaderboard cards.  
- Standardized **contributor profile display** (removed unnecessary "Top 50" heading – now shows all contributors in a clean list).  
- Updated **styles.css** with consistent styling for leaderboard section.  
- Added hover effects and subtle animations for better UX.  
- Improved dark mode compatibility.  
- Fixed API error handling to display user-friendly messages instead of console-only logs.  
- Makes the leaderboard more consistent and user-friendly.  
- Contributors’ profiles are displayed properly without confusing labels.  
- Provides a clean, responsive layout for …
=> 🏆 Leaderboard Page Fix & Enhancement  

contributors.html
Contributor List Page Improvements and Fixes  #1254 
The current Contributor List has several issues:  
- Layout inconsistency across different screen sizes.  
- No hover or focus effects on contributor cards, making the UI feel static.  
- Poor dark mode support (text/icons not visible).  
- No search or filter options, making it hard to find specific contributors.  
- Accessibility issues (missing alt text, no proper keyboard navigation).  
Implemented the following improvements:  
1. **Standardized Card Layout**  
- Unified contributor card structure with responsive grid system.  
- Ensures consistent appearance on all devices.  
2. **Hover & Focus Effects**  
- Added smooth hover animations (scale + shadow).  
- Improved focus states for keyboard navigation.  
3. **Dark Mode Support** …
=> Contributor List Improvements and Fixes 

editor.html, opaque_hover.html
Editor Page UI and Functionality Enhancements  #1256 
The current Editor page has several issues:  
- Layout inconsistencies across screen sizes.  
- Toolbar buttons lack proper hover/focus effects.  
- Dark mode support is partial or missing for some UI elements.  
- No clear error feedback for code execution failures.  
- Accessibility issues: missing labels, keyboard navigation issues.  
Implemented the following improvements:  
1. **UI/UX Enhancements**  
- Standardized layout for editor, console, and toolbar.  
- Added hover/focus effects for all buttons.  
- Responsive design for mobile and tablet screens.  
2. **Dark Mode Support**  
- Fixed colors for text, buttons, and console output.  
- Ensures visibility in both light and dark themes.  
3. **Error Handling**  
- Added clear …
=> Editor HTML Page Improvements  

editor.html, opaque_hover.html
Opaque on Hover Effect Not Working Properly – Animate It Now
Close #1257 
Certain elements in the Animate It Now project do not display the intended opacity change on hover. Users get inconsistent or missing visual feedback, which reduces interactivity and UX quality.
- Updated CSS rules for all hoverable elements to ensure opacity transitions are smooth and consistent.
- Added `transition: opacity 0.3s ease;` to relevant elements.
- Standardized hover effects across light and dark modes.
- Tested on multiple screen sizes to ensure responsiveness.
- `styles.css` / `main.css` (whichever is used):  
```css
.hover-element {
transition: opacity 0.3s ease;
}
.hover-element:hover {
opacity: 0.7; /* or desired opacity */
}
```
- Verified that all interactive elements now show the hover opacity …
=> Fixed : Opaque on Hover Effect Not Working Properly

index.html
The footer logo on the Home Page was missing due to an incorrect image reference or missing file. This caused the footer to look incomplete and reduced brand identity.  
Close : #1277 
- Corrected the `<img>` source path for the footer logo in `index.html`.  
- Verified that the logo image exists in the assets/images directory.  
- Added `alt` text for accessibility.  
- Ensured responsive scaling of the logo across devices.  
- Adjusted CSS for proper alignment within the footer.  
- **index.html**: Fixed the footer logo `<img>` source.  
- **styles.css**: Updated footer styling to align logo with other elements.  
The footer logo now displays properly, improving branding and making the footer visually complete.  
- Tested in both dark and light themes.  
- Verified responsiveness on …
=> Fix: Footer Logo Not Displaying on Home Page  

playground.html
Hover Effects Page Redesign and Functionality Enhancement – Animate It Now
Close : #1261
The current Hover Effects page has inconsistent styles, outdated effects, and lacks interactivity in some elements. Users experience:
- Uneven hover transitions across elements.
- Effects that don’t display properly in dark mode.
- Poor responsive behavior on mobile devices.
- Lack of visual feedback for interactive elements.
- Redesigned the Hover Effects page for a consistent look and feel.
- Unified all hover effect CSS into a single system for maintainability.
- Added smooth transitions for opacity, scale, and transform effects.
- Ensured dark mode support for all hoverable elements.
- Made the page fully responsive for mobile, tablet, and desktop screens.
- Added visual feedback (shadow, color …
=> Hover Effects Page Redesign and Functionality Enhancement – Animate It Now

templates/text_effects_anim.html
- Initially the Text effects components were just displaying the different styles without any further use.
- I added a minimal pop up to display the code snippet when click on the text effect card.
- Added copy button to copy the code in the pop up.
Fixes #1148 
https://github.com/user-attachments/assets/686f4fa9-0db1-4f13-a107-7f95b6018707
=> Enhanced Text Effects Page: Interactive Cards with Code Snippets, Themed Copy Button & Pointer Cursors

contributors.html, index.html
Description
Styled the subscribe button in the footer section to ensure proper alignment, spacing, and hover effects. The button now appears below the input field on smaller screens, is visually consistent with the site's theme, and is responsive.
Fixes #1263 
Type of Change
Bug Fix
Checklist
=> [BUG Fix] Style subscribe button in footer section properly.

.github/ISSUE_TEMPLATE/documentation.txt, .github/ISSUE_TEMPLATE/performance.txt
Added documentation and performance files in issue template in .github folder
=> Added documentation and performance files in issue template

index.html
=> Redesign the Cards on home page

templates.html, templates/404.html
The Templates section on the deployed website appears to be redirecting incorrectly. No animation templates are displayed, and the corrupted 404 file makes the website look bad.
So I fixed it.
Fixes #1320 
The 404 file was corrupted, so I added another improved version of it. A working animation of the ping pong game.
Befoure
After 
The redirection was not working correctly, so I fixed it, along with the corrupted 404 file, it was corrupted.
=> Fixed the Templetes and the 404 file

templates.html
Added a new **CSS Snippet Generator Template Card** to the template gallery for easy access.  
Fixes #1317 
This PR adds a **new template card** so users can quickly try out and preview CSS snippets alongside other templates.
=> Added CSS snippet generator template card

leaderboard.html
Close : #1329 
**Problem:**  
The current header/navigation bar has several issues:  
- Logo visibility is inconsistent across pages and devices.  
- Navigation links are misaligned or cluttered, particularly on mobile screens.  
- Hover effects and interactive feedback are missing or inconsistent.  
- Accessibility is limited (missing ARIA labels, focus states).  
- The design does not fully align with the website’s theme and style guide.
**Solution:**  
This PR implements a professional redesign of the header:  
1. Redesigned header layout for better logo visibility and brand emphasis.  
2. Aligned all navigation links with consistent spacing, hover effects, and dropdown behavior.  
3. Added fully responsive design for desktop, tablet, and mobile views.  
4. Implemented accessibility …
=> Header Component Redesign for Enhanced Navigation and UX

index.html, templates/LoadingSpinner.html, templates/scrollingAnimations.html
Scroll Animations was initially pointing to templates gallery but it should show different types of scrolling animations which are possible in websites. So in this i have added that..
Fixed #1297
=> Scroll animations templates added

index.html
Fixes #1309 
@AnujShrivastava01 @byamn
=> Fixed button transparency on index.html

index.html
**Issue Title:**  
Missing Images on Landing Page 📄
Close : #1350 
**Problem:**  
The landing page had several images that were not displaying correctly ❌. This made the page look incomplete and negatively impacted the visual experience for users.
**Solution:**  
- ✅ Verified and corrected all image paths in the landing page files.  
- 🖼️ Ensured proper imports for images stored in the assets folder.  
- 🔄 Replaced any broken or outdated image URLs.  
- ⚡ Optimized images for faster loading and responsive display.  
- 📱 Tested across devices to ensure images render correctly.
**Files Changed:**  
- src/pages/LandingPage.jsx (or index.html) – Updated image references and imports.  
- src/assets/images/ – Added missing images.  
- styles.css – Minor adjustments for responsive image display. …
=> Fix Missing Images on Landing Page 🖼️ (#1350)

templates.css, templates.html
1-> Added dropdown where the needed 
2->Make responsive also
3->set on break points for responsive navBar
Fixes #1338 
- [✅] Bug fix 🐛
- [✅] New feature ✨ 
- [✅] I have linked the issue using `Fixes #issue_number`
https://github.com/user-attachments/assets/791b33fa-845a-4e9b-b232-95759c7624d1
=> fixed navBar of template page

README.md
enchaned the readme
Fixes #1211
=> Improve Installation & Setup instructions in README

about.html, editor.html, playground.html, styles.css, templates.css
**Pull Request**
This PR fixes multiple navbar-related issues across various pages of the website:
**Contact Page:** Fixed navbar overflow and layout issues.
**Hover Effect Page:** Made navbar design consistent and aligned logo properly.
**Templates Page:** Improved navbar styling and positioning.
**About & Editor Pages:** Added missing logo and ensured correct alignment.
Improved overall responsiveness and styling for a clean, uniform look.
Fixes #1331
**Type of Change**
Bug fix (navbar design issues)
Code refactor (logo alignment and consistent styling)
**Checklist**
My code follows the style guidelines of this project
I have performed a self-review of my code
I have linked the issue using Fixes #1331
**Screenshots** 
**Related Issues**
Issue #1331
**Additional Context**
These updates …
=> fix: update navbar design across pages

templates/quotes.html, templates/tilt-card.html, templates/timer.html
Close : #1396 
This PR refactors and reorganizes the code in three template files to improve readability and maintainability without changing functionality.
Issue: Improve Code Organization and Readability
The changes include:
- Better structuring of CSS styles with consistent naming conventions
- Improved code organization with logical grouping of related styles
- Enhanced comments for better understanding of the codebase
- Streamlined HTML structure for better semantic markup
- No changes to the visual appearance or functionality of the components
These improvements will make the codebase easier to maintain and understand for future contributors while preserving all existing functionality.
1. templates/tilt-card.html
2. templates/timer.html
3. templates/quotes.html
=> Improve code organization and readability

index.html
Resized the padding sizes for input box [border size too] and subscribe button to make alignment proper
Fixes #1370
=> Resized Stay Updated box to make everything Visible

index.html
Fixed background inconsistencies - Removed gradient backgrounds from "Popular Animation Templates" and "Ready to Animate Your Website?" sections to maintain consistent theming
Fixes #1386 
Before:
After:
Theme consistency across homepage sections
User engagement through testimonials
Visual hierarchy and clean design
CSS Changes: Removed hardcoded gradients, replaced with CSS variables for theme consistency
JavaScript Enhancement: Added carousel logic with proper positioning calculations
Responsive Design: Maintained mobile compatibility with adjusted card sizes
Performance: Used CSS transforms for smooth hardware-accelerated animations
Accessibility: Added proper ARIA labels for screen readers
=> Enhanced the homepage design consistency

templates.css, templates.html
Description:
This PR updates the Templates page navbar with consistent styling across light/dark modes and responsive views.
Fixed alignment issues with logo, links, and dropdowns.
Unified desktop and mobile navigation design.
Improved dropdown hover effects and spacing.
Added responsive hamburger toggle for smaller screens.
Fixes #1246 
Type of Change
Bug fix
Checklist
Navbar is styled consistently across all pages
Light and dark modes are supported
Mobile and desktop views are properly aligned
Dropdown menus function smoothly
Code follows the style guidelines of the project
https://github.com/user-attachments/assets/479a754d-86f3-4e7c-a574-e504dce16118
=> Styled navbar for  template page consistently.

templates/sample-templates/marketing/index.html
Close : #1424 
This PR enhances the SEOBoost Marketing Agency website with emoji-based user interface elements to improve visual appeal and user engagement while maintaining all existing functionality.
- **Title Enhancement**: Added rocket emoji 🚀 to page title and brand
- **Navigation**: Enhanced nav links with relevant emojis (🛠️ Services, 📊 Stats, etc.)
- **Service Cards**: Added emojis to service titles and descriptions
- **Statistics**: Enhanced achievement metrics with visual emoji indicators
- **Testimonials**: Improved client feedback with emoji-enhanced quotes
- **Contact Form**: Enhanced form fields with descriptive emojis
- Maintained all existing counter animation functionality
- Preserved responsive design and layout structure
- Enhanced visual hierarchy without changing core …
=> 🚀 SEOBoost Agency Emoji UI Enhancement

background_templates/dark_starry_background.html
Close : #1418 
This PR enhances the Three.js starfield animation background with emoji title, improved code structure, better variable naming, and enhanced documentation while preserving all existing visual effects and performance.
- **Title Enhancement**: Added sparkle emoji ✨ to page title for cosmic theme
- **Variable Renaming**: More descriptive names (`cosmicScene`, `cosmicRenderer`, `cosmicTime`)
- **Code Documentation**: Enhanced comments throughout the codebase
- **Performance**: Added CSS optimization class
- **Animation Improvement**: Better structure for animation loop
- **Structure**: Improved code organization and logical separation
- Maintained all existing starfield visual effects and star count
- Enhanced code readability with descriptive naming conventions
- Improved …
=> ✨ Cosmic Starfield Animation Enhancement

templates/sample-templates/med/index.html
Close : #1426 
This PR enhances the MediCare healthcare website with emoji-based user interface elements to improve visual appeal and user engagement while maintaining all existing functionality.
- **Title Enhancement**: Added hospital emoji 🏥 to page title and brand
- **Navigation**: Enhanced nav links with relevant emojis (🛠️ Services, 👨‍⚕️ Doctors, etc.)
- **Doctor Cards**: Added emojis to doctor names, specialties, and features
- **Search Interface**: Enhanced search fields and filters with descriptive emojis
- **Booking Form**: Improved form labels and buttons with visual indicators
- **FAQ Section**: Enhanced questions and answers with emoji indicators
- Maintained all existing search and booking functionality
- Preserved responsive design and layout structure
- Enhanced visual …
=> 🏥 MediCare Website Emoji UI Enhancement

templates/sample-templates/shopping/shopify.html
close : #1433 
This PR introduces significant improvements to the StyleHub fashion store, enhancing user experience with new features and refined interactions while maintaining all existing functionality.
- **Product Quick View Modal**: Added detailed product preview without page navigation
- **Wishlist Functionality**: Implemented heart icons for saving favorite products with persistent storage
- **Enhanced Product Cards**: Added badges, ratings, and improved visual hierarchy
- **Search & Filtering**: Integrated real-time search and category filtering system
- **Loading Animations**: Enhanced cart animations and hover effects throughout
- **Cart Persistence**: Implemented localStorage for cart item persistence across sessions
- **Wishlist Management**: Added dedicated wishlist modal with …
=>  Enhancements and Shopping Experience Improvements

generator.css
Close : #1459 
This PR significantly enhances the CSS Generator tool with advanced styling options, responsive controls, and improved user experience while maintaining all existing functionality.
- **Gradient Generator**: Linear, radial, and conic gradients with color stops and angle controls
- **Shadow Controls**: Box-shadow and text-shadow with multiple layers, blur, spread, and color
- **Border Radius**: Individual corner controls with visual corner indicators
- **Transform Properties**: Rotate, scale, skew, and translate transformations
- **Transition Controls**: Duration, timing functions, and property-specific transitions
- **Breakpoint Generator**: Media query controls for mobile, tablet, and desktop
- **Flexbox Generator**: Visual flexbox controls with alignment and justification …
=> Enhanced CSS Generator with Advanced Styling Features

styles.css
=> Fix to inconsistent styled footer on contact us

about.html, components.html, contact.html, contributors.html, editor.html, index.html, leaderboard.html, navbar_styles.css, playground.html, pomodoro.html, templates.css, templates.html
The Navbar now is same across all the pages and which brings the website with consistency.
Fixes #1315 
Issue #1315 
I loved to work on this issue and looking forward to raise more issues.
=> Navbar Uneven Issue Resolved

templates.css, templates.html, templates.js
This PR applies small cosmetic and readability updates across 3 files in the templates system.
- Improved code organization with emoji comments
- Added non-functional placeholders and doc comments
- Slight CSS/UI tweaks for better maintainability
- Verified all behavior remains the same ✅
1. **templates.html** - Added emoji comments to HTML structure and meta tags
2. **templates.js** - Enhanced function documentation with emojis and added placeholder debug functions
3. **templates.css** - Improved CSS organization with emoji section headers and additional theme variables
- ✅ All template filtering functionality preserved
- ✅ Search feature working as expected
- ✅ Theme switching still functional
- ✅ Responsive design maintained
- ✅ No visual changes to UI, only code improvements
Close : …
=> Fix: Refactor: Improve Readability and Comments Across Templates System

leaderboard.html, templates/Coming_Soon_Landing_Page.html
The current "Coming Soon" template is visually appealing but lacks some professional web design elements and user-selectable variations.
To improve it, I add the following:
- Header Section: Include a site or brand logo/title and optional navigation links.
- Footer Section: Add contact info, copyright details, or social media links to the bottom.
- Template Options: Users can choose between multiple "Coming Soon" styles.
Fixes #1439 
Before: 
After:
=> enhanced the coming soon page

templates.html
Close : #1509 
This PR introduces code quality improvements to the templates page, focusing on better CSS variable organization and JavaScript naming conventions while maintaining identical functionality.
- **📝 Enhanced CSS Variables**: Improved naming with descriptive prefixes
- **🎯 Better JavaScript Naming**: More descriptive function and variable names
- **📚 Comprehensive Comments**: Added detailed code documentation
- **🏗️ Improved Organization**: Better CSS structure and grouping
- **🔧 Code Consistency**: Unified naming conventions throughout
- Zero functional changes to template filtering or display
- All animations and interactions remain identical
- Improved code maintainability and readability
- Better development experience
- Template search and filtering works identically
- …
=> 🎨 CSS Variable Organization and JavaScript Naming Improvements

test_card_system.html
Close: #1505 
This PR introduces code quality improvements to the card system test page, focusing on better CSS organization and animation naming while preserving all existing functionality.
- **📁 Better CSS Organization**: Restructured CSS with logical grouping and comments
- **🎯 Improved Naming**: Updated animation names for better clarity (float → floatAnimation)
- **📝 Enhanced Documentation**: Added comprehensive code comments throughout
- **🔧 JavaScript Refinements**: Improved variable naming and added initialization logging
- **✨ Ripple Enhancement**: Dedicated keyframes for ripple effect
- Zero visual or functional changes
- All animations and interactions preserved
- Improved code maintainability
- Better development experience
- All card animations work identically
- Filter …
=> 🎨 CSS Structure Enhancement and Animation Improvements

templates/Animation.html, templates/Animation.js, templates/scrollingAnimations.html
In this template of Scrolling Animations, when clicked on view template of different templates in it it was not opening. So in this pr  i have added in which all the view templates are working and linking it to that respective templates and their respective codes...
Fixed #1399
=> Templates Of scrolling animations added

index.html
**Fixes #1455 and #1453 **
This Pull Request introduces **two major visual enhancements** to the `index.html` homepage to significantly improve aesthetic appeal and user experience:
1.  **Navigation Hover Glow (Fixes #1455):** Implements a smooth, high-quality interactive hover effect for all main navigation links.
2.  **Subtle Fluid Background:** Adds a full-screen, performant, ambient animation to the homepage background.
---
* **Implements:** A smooth color change, text-shadow glow, and subtle vertical lift (`transform: translateY(-2px)`).
* **Effect:** Uses CSS gradients for the text color and the `::after` pseudo-element for a growing gradient underline, providing a modern and interactive user experience.
* **Feature:** Adds a full-screen, slow-moving **Geometric Plasma** effect …
=>  Add smooth color and text-shadow glow hover effect to nav links and Subtle Dynamic Gradient Mesh

components.js
Fixes #1457 
->Added new component card in component section
->Added animated grid background 
->added it's preview , code , usages, customization
- [✅] New feature ✨ 
- [V] I have linked the issue using `Fixes #1457`
=> Added new component animated grid-background

ai-assistant/script.js
Close : #1520 
This PR introduces comprehensive improvements to the AI Assistant JavaScript, focusing on documentation quality, error handling, and functionality enhancements while maintaining 100% backward compatibility.
- **Enhanced function documentation** with detailed JSDoc comments
- **Improved code organization** with logical function grouping
- **Comprehensive inline comments** explaining complex logic
- **Better variable naming** for clarity and consistency
- **Improved error handling** for voice recognition
- **User-friendly error messages** with specific guidance
- **Data loading fallback** when JSON file fails
- **Graceful degradation** for unsupported features
- **Visual feedback** during recording
- **Better error states** for microphone issues
- **Improved browser …
=> 🎯 AI Assistant JavaScript Enhancement

ai-assistant/index.html
Close : #1517 
This PR introduces comprehensive HTML improvements to the AI Assistant interface, focusing on documentation quality, semantic structure, and accessibility while maintaining 100% backward compatibility.
- **Enhanced HTML documentation** with descriptive comments
- **Improved semantic structure** with clear section organization
- **Better code organization** with logical component grouping
- **Comprehensive section labeling** for better understanding
- **Proper alt tags** for images and icons
- **Semantic HTML structure** for screen readers
- **Clear element hierarchy** for better navigation
- **Accessible form controls** with proper labeling
- **Clear component documentation** explaining each section
- **Consistent naming conventions** throughout
- **Logical flow …
=> 🎨 AI Assistant HTML Structure Enhancement

templates/404.html
Close : #1522 
This PR introduces comprehensive improvements to the 404 Ping Pong Game template, focusing on documentation quality, accessibility enhancements, and code organization while maintaining 100% backward compatibility.
- **Enhanced HTML structure** with semantic elements and accessibility
- **Comprehensive CSS documentation** with organized styling sections
- **Improved JavaScript documentation** with detailed function explanations
- **Better code organization** with logical section grouping
- **ARIA labels and roles** throughout the template
- **Screen reader support** for game elements and navigation
- **Keyboard navigation** enhancements
- **Semantic HTML structure** for better accessibility
- **Comprehensive code documentation** with explanations
- **Implementation guide** …
=> 🎯 404 Ping Pong Game Template Enhancement

contact.html
Enhanced the card layout with the following improvements for a more visually appealing and user-friendly interface:
1.Beautiful gradient backgrounds with subtle borders
2.Centered text for better alignment and readability
3.Larger font size (1.05rem) to improve text clarity
4.Hover effects — cards lift and glow when hovered
5.Responsive Design:
6.Adaptive font sizes across devices for consistent readability
7.Touch-friendly buttons for improved mobile usability
Fixes #1511 
Before:
After:
Related to: #1511
This update enhances visual aesthetics, accessibility, and responsiveness across devices — improving user experience while keeping the design consistent and modern.
=> Enhanced contact page

index.html
📄 Description
This PR fixes the issue where clicking the logo did not redirect to the Home page. Now, clicking the logo correctly navigates users to the Home page of the site.
Fixes #1529 
🛠️ Type of Change
Bug fix 🐛
✅ Checklist
My code follows the style guidelines of this project
I have performed a self-review of my code
I have commented my code, particularly in hard-to-understand areas
I have tested the fix to ensure it works as expected
I have linked the issue using Fixes #1529
📚 Related Issues
Fixes #1529
🧠 Additional Context
This fix improves user navigation by ensuring a consistent way to return to the Home page from any page within the app.
=> Redirect to Home
