index.html, styles.css
- Added a List Group in 'index.html'
- Removed defaults bullets by styling'. List-group-item' in 'styles.css'
Fixes #{ISSUE_15}
**![screenshot]<img width="1891" height="906" alt="screenshot" src="https://github.com/user-attachments/assets/60144366-f680-4915-a1e6-295be3dfbe3d" />
none
=> Added list group and improved styles in styles.css

templates.html
Fixes #29 
1. Dark Mode Styling for Template Cards
- Introduced new CSS rules targeting .template-card, .template-preview, .template-btn and their headings (h2) to match dark backgrounds.
- Improved border visibility and hover effects with theme-aware accents.
2. Text Visibility Enhancements
- Made sure key text elements—like “Templates Gallery,” template titles, and buttons—switch to white in dark mode using body.dark-theme overrides.
- Added smooth transition effects for color and background changes.
3. Navbar Theme Integration
- Ensured navbar background and text adapt to dark theme.
- Applied brightness() and contrast() filters to the logo for clarity in dark mode.
- 4. Consistent Background & Layout Handling
- Updated .templates-main and .templates-grid to shift background shades …
=>  Fix: Template gallery visibility in dark mode

styles.css
Fixes #176
Resolved the footer restacking and overlapping issue on mobile devices by updating the layout and applying appropriate media queries in the CSS.
**Before**
<p align = "center">  
</p>
**After**
<p align = "center">
</p>
None
This PR improves the user experience on mobile by ensuring the footer behaves responsively and aligns with the content layout correctly.
=> Fix: Footer layout issue on mobile view

styles.css
This PR ensures that template section headings are clearly visible when dark mode is enabled by applying appropriate color adjustments.
Previously addressed in PR #183 but lost due to fork deletion. This is a clean re-PR.
✅ Dark mode styles updated  
✅ Verified in both light and dark themes
closes #96
=> Fix: Template section headings are now visible in dark mode

script.js
Fixed the broken contributors section by updating the GitHub API URL to the correct repository: `itsAnimation/AnimateItNow`.
Fixes #197
- N/A
This fix enables real-time contributor data to be fetched and displayed correctly on the site using the GitHub API.
=> Fix: Correct GitHub Contributors API Endpoint for Live Data

contact.html
I have added placeholders in contact form fields so that it gives detailed description to users about what to enter in the fields.
Please merge this request.
Solved issue #147
=> Added placeholders in contact form fields

styles.css
Fixed the footer color mismatch issue in dark mode by updating the footer background and text color styles accordingly.
Fixes #287
This fix ensures the footer blends properly with the rest of the dark mode theme, improving overall UI consistency and user experience.
=> Fix: Update footer background to match dark mode aesthetics

about.html, templates.html
Fixes #515 
--> and dark theme logo in about is already fixes
- [✅] I have linked the issue using `Fixes #515`
=> about and templates make active on clicking and dark mode icon visible

styles.css, templates.html
This PR adds a user-friendly message and corresponding styling to handle cases where no templates are found in the search results. 
- 🔍 **Empty State Logic**  
Conditional rendering in `templates.html` to check if search results are empty.
- 🖼️ **User Message Display**  
Shows the text **"No templates found."** in a user-friendly format.
- 🎨 **Styling**  
CSS added in `styles.css` to style the message consistently with the app's UI.
---
1. Navigate to the **templates** or **search** page.
2. Enter a keyword that does **not match any templates**.
3. You should see the following message styled on screen:
> **No templates found.**
---
- `templates.html`  
- Added conditional logic for empty search state  
- Added markup to display message
- `styles.css`  
- Added `.no-results` class for …
=> Created a message and styling for no templates found.

index.html, styles.css
Added LinkedIn link to the Project Admin's name in the footer , when the name is hovered , it redirects to his LinkedIn when pressed on hover button.
Fixes #{347}
=> Added link to the Project Admin's name on hover

index.html
- Fixed a layout bug in the FAQ section where one question card was overlapping or nested inside another.
- Ensured each FAQ item is displayed within its own distinct, properly spaced card.
- Reviewed and corrected any misused or missing HTML tags and verified flex/grid structure.
- Improved overall visual structure and readability.
Closes #733 @AnujShrivastava01
=> 🔧 Fix: Resolved FAQ Card Overlap Issue

leaderboard.html, templates.html
This PR fixes a **bug** where the "Hover-Effects" link was missing from the main navigation bar on the `/templates` and `/leaderboard` pages. The link has been added to ensure the navbar is **consistent** across the entire website. ✨
Fixes #805 
---
---
---
before:
After :
---
This change improves the overall user experience by ensuring navigational consistency.
=> Fix: Added missing hover effect to navbar on Templates and Leaderboard pages

playground.html, styles.css
Adds functional hover effects for all box elements with separate styles for light and dark themes.  
Hover interactions now change background, text color, and box-shadow dynamically based on the active theme.
Fixes #892 
https://github.com/user-attachments/assets/a6cf5707-3872-4ee9-99aa-1103626fbdf9
Closes #892
=> Functional hover Effect Section

styles.css
Fixes #801  
This PR resolves the **logo text animation glitch** where the typing effect on the site name caused other navbar elements to shift repeatedly.  
The fix applies a `min-width` to the left navbar section (`.nav-left`), ensuring the space for the animated logo text remains constant throughout the typing cycle.  
This prevents layout reflows and keeps the rest of the navigation bar stable while the animation runs.
**Before:**  
Navbar elements shift left/right with each typing loop.  
*Already added to the issue description*
**After:**  
https://github.com/user-attachments/assets/5528e033-3a58-495d-93ba-a5037f519149
- Closes #801
- Solution: Set `min-width` on `.nav-left` to reserve space for the logo text.  
- Maintains responsive behavior across breakpoints.  
- Typing …
=> [FIX]: #801 Logo Typing Animation Causes Layout Shift in Navbar 

leaderboard.html
Improved the visual contrast of the Leaderboard section in Dark Mode to enhance readability and UI clarity. Updated background and text colors to align with the overall theme while ensuring sufficient contrast.
Fixes #789 
Before--
After--
None
The changes were made to maintain visual consistency in dark mode and improve accessibility for users with visual strain. Let me know if you’d like any further adjustments!
=> fix: improve contrast in leaderboard section for better dark mode visibility

.vscode/settings.json, index.html, script.js, styles.css
-Fixed the FAQ toggle functionality so clicking a question now properly shows/hides the answer.
-Also enhanced the layout by centering the FAQ title and subtitle for better visual balance.
Fixes #958 
#Before 
#After 
Possibly related to FAQ section interactivity issue in earlier commits.
While fixing the FAQ toggle bug, improved code by making toggleFAQ globally accessible and ensuring only one FAQ item stays open at a time.
=> Fix FAQ answers toggle and center title/subtitle

templates/toggles-and-checkboxes.html
This PR resolves the issue of missing code for four Animated toggles templates: Gooey Liquid Toggle, 3D Flip Checkbox, Illuminating Toggle, Dynamic Stroke Checkbox. I have resolved the missing code issues for these four templates.
Changes include:
- Resolved missing code issues for four key animation templates, making them fully functional and accessible to users.
- Ensured all new components are provided as clean, easy-to-copy HTML and CSS snippets, fulfilling the educational purpose of the project.
Fixes #782 
- [✅] Bug fix 🐛
- …
=> Updated four Animated toggles templates

templates/button.html
This PR fixes the non-functional template items on the Templates page by adding interactive code previews and a copy-to-clipboard feature. This significantly enhances the user experience by making the code for each button effect easily accessible.
- **Interactive Button Cards:** Implemented a "Show Code" button for each button effect.
- **Code Toggle:** Clicking "Show Code" now reveals a detailed HTML + CSS snippet.
- **Copy Functionality:** Added a "Copy" button to each code block, which provides visual feedback when the code is copied.
- **Dynamic Content:** Only one code section can be open at a time, ensuring a clean and focused interface.
1. Navigate to the `templates.html` page.
2. Click the "📋 Show Code" button on any button effect card (e.g., "Glow Effect," "Rainbow Glow").
3. …
=> ✨ Added copy-to-clipboard feature to button.html for easier code access

styles.css
-This PR ensures that gradient text displays correctly across all major browsers.
Closed #1230 
- Bug fix 🐛
- Added the standard background-clip: text property alongside -webkit-background-clip: text.
-Used color: transparent and -webkit-text-fill-color: transparent to ensure proper rendering.
-Tested on Chrome, Safari, Edge, and Firefox for consistency
-Gradient text now appears correctly in all supported browsers.
-Improves visual consistency and user experience across devices.
=> Fixed gradient text CSS for cross-browser compatibility

leaderboard.html
The site logo was missing from the **Leaderboard page**, making the navigation header inconsistent with other pages.  
Close : #1279 
- Added the correct `<img>` source for the logo in `leaderboard.html`.  
- Applied existing `logo` CSS class from global styles for consistent design.  
- Ensured responsiveness and alignment with other navbar elements.  
- Added `alt` text for accessibility.  
- **leaderboard.html** → Inserted site logo in the header/footer.  
- **styles.css** → Verified consistent logo styling.  
The **Leaderboard page** now displays the logo properly, creating a consistent and professional look across all pages.  
- Tested in desktop and mobile view.  
- Works in both light and dark mode.
=> Fix: Leaderboard Page Logo Not Displaying  

index.html, templates/LoadingSpinner.html
Loading spinner was initially pointing to templates gallery. But in actually it should point to different types of loading spinners which can be used in different websites. So, in this i have added that when user will click on view template of loading spinner it will point to different types of loading spinners which are possible..
Fixed #1296
=> Load spinner added

index.html
The spacing between the elements of the navbar at the Homepage was not properly aligned which is managed now.
Fixes #1313 
Previously:
After changes:
I have another related issue which i will be resolving in other request.
I loved to work on this issue and towards this project and looking forward to raise more issue to help in improving the great project. @gssoc2025
=> Navbar Hompage Spacing Resolved

editor.html, index.html, opaque_hover.html
Added a scroll to top button to index.html and opaque_hover.html.
Previously the scroll to top button at the bottom right corner was only available on the about page
Fixes #1349
=> Added scroll to top button

templates.css, templates.html
Added a favorites feature to the templates gallery. Users can click the star icon on each template card to mark it as a favorite. Favorites are stored in localStorage and persist across page reloads. Updated filtering to include a Favorites filter button
Fixes #1356 
#1356 
Clicking the star updates UI dynamically.
Favorites filter displays only selected templates.
=>  Enable users to mark templates as favorites

templates.css
- Fixed the footer with proper spacing in between 
Fixes #1450 
- Bug fix 🐛
- New feature ✨
- Code refactor 🔨
- My code follows the style guidelines of this project
- I have performed a self-review of my code
- I have commented my code, particularly in hard-to-understand areas
- I have added tests that prove my fix is effective or that my feature works
- I have linked the issue using `Fixes #issue_number`
<h1>Before</h1>
<h1>After</h1>
=> Fixed the footer on Templates page
